name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4

    # Set up JDK 11 instead of JDK 17
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'  # Change from 17 to 11
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    # Build the project using Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Extract artifactId and version from pom.xml
    - name: Extract project information from pom.xml
      id: project-info
      run: |
        ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    # Upload the JAR file to the release
    - name: Upload JAR to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/${{ env.ARTIFACT_ID }}-${{ env.VERSION }}.jar
        asset_name: ${{ env.ARTIFACT_ID }}-${{ env.VERSION }}.jar
        asset_content_type: application/java-archive
